### ISSUE TITLE
Failed to send POST for group using Slack Webhook

### ISSUE THREAD

**Issue by anishmashankar** [linkedin/Burrow#103]
I am using a slack webhook URL to post Burrow alerts. My configurations for the [httpnotifier] is

> [httpnotifier]
> url=https://hooks.slack.com/services/web-hook-endpoint
> interval=60
> template-post=/mnt/http-post.tmpl
> send-delete=false
> template-delete=/mnt/http-delete.tmpl
> timeout=5
> keepalive=30
> post-threshold=1
> 

And here is my post template:
`{  "text": "alert from burrow. status on {{call .JsonEncode .Group}} is {{.Result.Status.String}}" }`

The configuration looks fine to me, and the request body works when I issue requests using CURL. This, however, throws the following error in burrow logs:

`2016-08-04 11:41:20 [ERROR] Failed to send POST for group consume-group in cluster stage at severity OK (Id ): 400 Bad Request`

Am I doing something wrong here?

**Comment by toddpalino** [comment]
You're calling `{{call .JsonEncode .Group}}` within a string, and that's the problem. The output from that will have double quotes in it (since it's JSON), so you're ending up sending something to the endpoint that is not valid JSON, which is why you're getting a 400 back. You'll need to more carefully construct the string to send to Slack.

Alternately, a Slack notifier module has been merged into master now, so you can pull that and try it. There's no documentation added for it yet, however.
