### ISSUE TITLE
Richer documentation for lag and status endpoints

### ISSUE THREAD

**Issue by Lawouach** [linkedin/Burrow#104]
Hi guys,

I have started using Burrow for a few days and thought the getting started was simple enough. I have found the documentation about the lag/status endpoints to be too light.

https://github.com/linkedin/Burrow/wiki/http-request-consumer-group-status

More specifically, would it be possible to describe a little more the various fields:
- totallag: looking at the source, it seems to be added lag of all partitions for that group. Is this correct? Can we use this has a quick and dirty flag to check the overall health of a group?
- start and end structures are not really explained and I'm not sure how I could go and use them. I thought I could plot the diff of timestamps so that I could keep an eye on that. Is that helpful you think?
- maxlag: in my setup, it's always `null` but I can't say this relates closely to the description given in the wiki page so I'm not sure how I should interpret that `null` value.

Thanks,

**Comment by Lawouach** [comment]
Also, would you advise an appropriate rate at which polling those endpoints would be the most effective?

**Comment by pavansai8** [comment]
I'm getting below response when I'm trying to check lag for consumer groups. It is not showing detailed report. Can someone help me on this.

http://nj09mhf5528.mhf.mhc:8000/v2/kafka/DevCluster/consumer/testgroup123/lag

{
"error": false
"message": "consumer group status returned"
"status": {
"cluster": "DevCluster"
"group": "testgroup123"
"status": "OK"
"complete": false
"partitions": [0]
"partition_count": 1
"maxlag": null
"totallag": 0
}-
"request": {
"url": "/v2/kafka/DevCluster/consumer/testgroup123/lag"
"host": "nj09mhf5528.mhf.mhc"
"cluster": "DevCluster"
"group": "testgroup123"
"topic": ""
}-
}

**Comment by toddpalino** [comment]
@pavansai8, I really need you to not attach your questions and issues to every other issue. It becomes very hard to work through problems. As I have stated separately, what you're pasting in is not a response from Burrow. It's not JSON, and it's not complete. Open a separate issue please and work that one issue.

**Comment by toddpalino** [comment]
@Lawouach 
Thanks for the feedback! You're right, the docs are a little light here and could do with updating. You're correct on totallag, though I would not use it as the indicator. That's what the status field is for - it tells you whether any partitions are in a bad state (lagging, stopped, etc.).

Start and end are the starting and ending offset commits for the partition that Burrow knows about. It's the timestamp of the offset commit, the offset that was committed, and the lag calculated at that time. It should give you an idea of the progress that the consumer is making.

Maxlag is the partition that is lagging the most out of the consumer group. If it's null, that's generally because your group information is not complete yet (the `complete` flag will be false), which means there aren't enough offset commits yet to do a full evaluation.

As far as polling goes, probably every minute is sufficient. Remember that hitting the endpoint performs an evaluation of the consumer group, so there's some work going on in the background every time you poll it.

**Comment by pavansai8** [comment]
Todd,

Thanks, I Will open a separate ticket for each issue.

**Comment by Lawouach** [comment]
Thanks @toddpalino for the feedback. This is helpful indeed and clarified my understanding. Hopefully, you guys get to update the doc at some point :)
