### ISSUE TITLE
How to configure Email alerts in burrow. Can someone guide me what values to be given in below segement.

### ISSUE THREAD

**Issue by pavansai8** [linkedin/Burrow#111]
[smtp]
server=mail03-m.edmz.mcgraw-hill.com
port=25
username=pbhaskaruni@spglobal.com
password=P@ssw0rd8
from=burrow-noreply@example.com
template=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-email.tmpl

[email "pbhaskaruni@spglobal.com"]
group=DevCluster,critical-consumer-group
group=DevCluster,other-consumer-group
interval=60

**Comment by jsvisa** [comment]
Sorry, after Burrow updated, the snippet in [config/burrow.cfg](https://github.com/linkedin/Burrow/blob/master/config/burrow.cfg) is not updated, you need to alert `email` to `emailnotifier` like below:

```
[emailnotifier "pbhaskaruni@spglobal.com"]
group=DevCluster,critical-consumer-group
group=DevCluster,other-consumer-group
interval=60
```

**Comment by jsvisa** [comment]
Also see #107 for more information

**Comment by pavansai8** [comment]
Bro, Can you also help me on this E-mail notification.

**Comment by jsvisa** [comment]
Sorry, that's impossible, are you compile `Burrow` using the newest code base

**Comment by pavansai8** [comment]
I took the burrow code on Feb 17th. I'm not sure if changes happened after that.

kafka_2.11-0.10.0.0 is my kafka version I'm using by the way.

**Comment by jsvisa** [comment]
No, you need to pull the newest code base

**Comment by pavansai8** [comment]
You are asking me to complie to code again?? :( It took so much time for me during first compilation as I faced number of issues.

**Comment by pavansai8** [comment]
Still I'm facing same issue dear. I compiled the latest code of burrow.
During compliation it said 

[pbhaskaruni@nj09mhf5527 linkedin]$ /home/pbhaskaruni/gpm/bin/gpm install
>> Godeps file does not exist.
>> All Done
[pbhaskaruni@nj09mhf5527 burrow]$ /home/pbhaskaruni/go/bin/go install

Reading configuration from ../home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/burrow.cfg
2016/08/12 07:53:48 Failed to parse gcfg data: invalid section: section "emailnotifier"

**Comment by jsvisa** [comment]
You need to fetch the latest code from remote first, then compile 
            On 08/12/2016 19:56, pavansai8 wrote:Still I'm facing same issue dear. I compiled the latest code of burrow.
During compliation it said 

[pbhaskaruni@nj09mhf5527 linkedin]$ /home/pbhaskaruni/gpm/bin/gpm install



Godeps file does not exist.
All Done
[pbhaskaruni@nj09mhf5527 burrow]$ /home/pbhaskaruni/go/bin/go install



Reading configuration from ../home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/burrow.cfg
2016/08/12 07:53:48 Failed to parse gcfg data: invalid section: section "emailnotifier"

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linkedin/Burrow","title":"linkedin/Burrow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linkedin/Burrow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pavansai8 in #111: Still I'm facing same issue dear. I compiled the latest code of burrow.\r\nDuring compliation it said \r\n\r\n[pbhaskaruni@nj09mhf5527 linkedin]$ /home/pbhaskaruni/gpm/bin/gpm install\r\n\u003e\u003e Godeps file does not exist.\r\n\u003e\u003e All Done\r\n[pbhaskaruni@nj09mhf5527 burrow]$ /home/pbhaskaruni/go/bin/go install\r\n\r\nReading configuration from ../home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/burrow.cfg\r\n2016/08/12 07:53:48 Failed to parse gcfg data: invalid section: section \"emailnotifier\""}],"action":{"name":"View Issue","url":"https://github.com/linkedin/Burrow/issues/111#issuecomment-239427899"}}}

**Comment by jsvisa** [comment]
And it won't take much time to compile again, the first time, gmp need to fetch all sub dependiences, while in the later ones, this step is skipped 
            On 08/12/2016 19:01, pavansai8 wrote:You are asking me to complie to code again?? :( It took so much time for me during first compilation as I faced number of issues. 

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linkedin/Burrow","title":"linkedin/Burrow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linkedin/Burrow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pavansai8 in #111: You are asking me to complie to code again?? :( It took so much time for me during first compilation as I faced number of issues. \r\n"}],"action":{"name":"View Issue","url":"https://github.com/linkedin/Burrow/issues/111#issuecomment-239419051"}}}

**Comment by pavansai8** [comment]
[general]
logdir=/home/pbhaskaruni
logconfig=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=nj09mhf5527.mhf.mhc
hostname=nj09mhf5528.mhf.mhc
hostname=nj09mhf5529.mhf.mhc
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "DevCluster"]
broker=nj09mhf5527.mhf.mhc
broker=nj09mhf5528.mhf.mhc
broker=nj09mhf5529.mhf.mhc
#broker=kafka04.example.com
#broker=kafka05.example.com
broker-port=9092
zookeeper=nj09mhf5527.mhf.mhc
zookeeper=nj09mhf5528.mhf.mhc
zookeeper=nj09mhf5529.mhf.mhc
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets

#[storm "DevCluster"]
#zookeeper=nj09mhf5527.mhf.mhc
#zookeeper=nj09mhf5528.mhf.mhc
#zookeeper=nj09mhf5529.mhf.mhc
#zookeeper-port=2181
#zookeeper-path=/kafka-cluster/stormconsumers

[tickers]
broker-offsets=60
[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800
min-distance=1
zookeeper-interval=60
zk-group-refresh=300

[httpserver]
server=on
port=8000

[smtp]
server=mail03-m.edmz.mcgraw-hill.com
port=25
username=pbhaskaruni@spglobal.com
password=P@ssw0rd8
from=burrow-noreply@example.com
template=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-email.tmpl

[emailnotifier "pbhaskaruni@spglobal.com"]
group=DevCluster,critical-consumer-group
group=DevCluster,other-consumer-group
interval=60

[notify]
interval=10

[httpnotifier]
url=http://notification.server.example.com:9000/v1/alert
interval=60
extra=app=burrow
extra=tier=STG
template-post=config/default-http-post.tmpl
template-delete=config/default-http-delete.tmpl
timeout=5
keepalive=30

[slacknotifier]
enable=true
url=https://hooks.slack.com/services/xxxx/xxxxxxxxxx
group=local,critical-consumer-group
group=local,other-consumer-group
threshold=0
channel="#general"
username=burrower
interval=5
timeout=5
keepalive=30


Did you find any mistakes in my configuration friend?

**Comment by pavansai8** [comment]
And is GODEPS mandatory??

It throwed this message during my recent compilation.

**Comment by jsvisa** [comment]
hi, @pavansai8 It's ok right now?

**Comment by pavansai8** [comment]
Hi Friend,

Still I'm having the same issue after compiling the latest burrow code.
Can you help me.

**Comment by pavansai8** [comment]
Hi Jsvisa,

Now the error was gone. I have successfully compiled the latest burrow code.
But still I'm not receiving any E-mail. Can you check my configuration once.
I'm using Advanced Rest client to send http requests.

[general]
logdir=/home/pbhaskaruni/Burrow_logs
logconfig=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=nj09mhf5527.mhf.mhc
hostname=nj09mhf5528.mhf.mhc
hostname=nj09mhf5529.mhf.mhc
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "DevCluster"]
broker=nj09mhf5527.mhf.mhc
broker=nj09mhf5528.mhf.mhc
broker=nj09mhf5529.mhf.mhc
#broker=kafka04.example.com
#broker=kafka05.example.com
broker-port=9092
zookeeper=nj09mhf5527.mhf.mhc
zookeeper=nj09mhf5528.mhf.mhc
zookeeper=nj09mhf5529.mhf.mhc
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets

#[storm "DevCluster"]
#zookeeper=nj09mhf5527.mhf.mhc
#zookeeper=nj09mhf5528.mhf.mhc
#zookeeper=nj09mhf5529.mhf.mhc
#zookeeper-port=2181
#zookeeper-path=/kafka-cluster/stormconsumers
[tickers]
broker-offsets=60

[lagcheck]
intervals=1
expire-group=604800
min-distance=1
zookeeper-interval=60
zk-group-refresh=300

[httpserver]
server=on
port=8000

[smtp]
server=mail03-m.edmz.mcgraw-hill.com
port=25
from=burrow-noreply@example.com
template=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-email.tmpl

[emailnotifier "pbhaskaruni@spglobal.com"]
group=DevCluster,critical-consumer-group
group=DevCluster,other-consumer-group
interval=60

[notify]
interval=10

[httpnotifier]
url=http://notification.server.example.com:9000/v1/alert
interval=60
extra=app=burrow
extra=tier=STG
template-post=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-http-post.tmpl
template-delete=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-http-delete.tmpl
timeout=5
keepalive=30

[slacknotifier]
enable=true
url=https://hooks.slack.com/services/xxxx/xxxxxxxxxx
group=DevCluster,critical-consumer-group
group=DevCluster,other-consumer-group
threshold=0
channel="#general"
username=burrower
interval=5
timeout=5
keepalive=30

**Comment by jsvisa** [comment]
First of all, you need to ensure the consumer is living and consuming, you can use [this endpoint](https://github.com/linkedin/Burrow/wiki/http-request-consumer-group-status) to find out.

If not alerted, maybe the consumer is in the health state, or maybe you need to reduce the `threshold`.

Maybe help you.

**Comment by pavansai8** [comment]
Hi Jsvisa,

Thanks for your help. There are no errors after compiling the new code.
Will I get E-mail If the consumer is not in a good state? And at what interval the E-mails are triggered.
And I asked my linux server team to share me the SMTP details of our server.
you said about threshold? Where can I find this value?

**Comment by jsvisa** [comment]
No no no, I mean the threshold of you configed one, not the Email server's configured one 
            On 08/18/2016 17:45, pavansai8 wrote:Hi Jsvisa,

Thanks for your help. There are no errors after compiling the new code.
Will I get E-mail If the consumer is not in a good state? And at what interval the E-mails are triggered.
And I asked my linux server team to share me the SMTP details of our server.
you said about threshold? Where can I find this value? 

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linkedin/Burrow","title":"linkedin/Burrow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linkedin/Burrow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pavansai8 in #111: Hi Jsvisa,\r\n\r\nThanks for your help. There are no errors after compiling the new code.\r\nWill I get E-mail If the consumer is not in a good state? And at what interval the E-mails are triggered.\r\nAnd I asked my linux server team to share me the SMTP details of our server.\r\nyou said about threshold? Where can I find this value? "}],"action":{"name":"View Issue","url":"https://github.com/linkedin/Burrow/issues/111#issuecomment-240675345"}}}

**Comment by pavansai8** [comment]
I have not configured any threshold value. :(

**Comment by Febeoro** [comment]
but when I download the newest code, it still have the " Godeps file does not exist." problem. I just wander know ,is there any chance that i can use it?

**Comment by kevinsingapore** [comment]
> 
> 
> but when I download the newest code, it still have the " Godeps file does not exist." problem. I just wander know ,is there any chance that i can use it?

you need to install godep，more information to see https://github.com/tools/godep
