### ISSUE TITLE
Hi, Can someone tell me how to use the Http notifier and Slact notifier in burrow.cfg.

### ISSUE THREAD

**Issue by pavansai8** [linkedin/Burrow#114]
[httpnotifier]
url=http://notification.server.example.com:9000/v1/alert
interval=60
extra=app=burrow
extra=tier=STG
template-post=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-http-post.tmpl
template-delete=/home/pbhaskaruni/work/go/src/github.com/linkedin/burrow/config/default-http-delete.tmpl
timeout=5
keepalive=30

[slacknotifier]
enable=true
url=https://hooks.slack.com/services/xxxx/xxxxxxxxxx
group=DevCluster,critical-consumer-group
group=DevCluster,other-consumer-group
threshold=0
channel="#general"
username=burrower
interval=5
timeout=5
keepalive=30

**Comment by devsprint** [comment]
I'm also looking for an answer to this question. As far as I have investigated so far, the slack notification feature is not completed.

**Comment by jsvisa** [comment]
@devsprint Slack notifier runs well

**Comment by devsprint** [comment]
@jsvisa than I probably do something wrong. As soon as I add the [slacknotifier] section to config file  , Burrow is not starting anymore (running in docker). If I try to run it outside container from command line (following the instruction on github) I always getting: 
`Reading configuration from burrow.cfg
2016/08/18 08:43:38 Failed to parse gcfg data: invalid section: section "slack notifier"`

**Comment by pavansai8** [comment]
Hi,

What is the use of this slack notifier?

**Comment by jsvisa** [comment]
Show me the config file 
            On 08/18/2016 13:44, Gabriel Ciuloaica wrote:@jsvisa than I probably do something wrong. As soon as I add the [slacknotifier] section to config file  , Burrow is not starting anymore (running in docker). If I try to run it outside container from command line (following the instruction on github) I always getting: 
Reading configuration from burrow.cfg
2016/08/18 08:43:38 Failed to parse gcfg data: invalid section: section "slack notifier"

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linkedin/Burrow","title":"linkedin/Burrow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linkedin/Burrow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@devsprint in #114: @jsvisa than I probably do something wrong. As soon as I add the [slacknotifier] section to config file  , Burrow is not starting anymore (running in docker). If I try to run it outside container from command line (following the instruction on github) I always getting: \r\n`Reading configuration from burrow.cfg\r\n2016/08/18 08:43:38 Failed to parse gcfg data: invalid section: section \"slack notifier\"`\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/linkedin/Burrow/issues/114#issuecomment-240629340"}}}

**Comment by jsvisa** [comment]
Another tool for notification 
            On 08/18/2016 18:02, pavansai8 wrote:Hi,

What is the use of this slack notifier?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linkedin/Burrow","title":"linkedin/Burrow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linkedin/Burrow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pavansai8 in #114: Hi,\r\n\r\nWhat is the use of this slack notifier?"}],"action":{"name":"View Issue","url":"https://github.com/linkedin/Burrow/issues/114#issuecomment-240679625"}}}

**Comment by pavansai8** [comment]
Can you tell me how to use it. Even I'm didn't get familiar with Httpnotifier also.
Will you help me how to use those two configurations. I have to present a demo on this kafka today.
