### ISSUE TITLE
Status endpoint returns complete:false and no partitions, but consumer+topic offsets are available.

### ISSUE THREAD

**Issue by iamnoah** [linkedin/Burrow#12]
(Sorry, this feels more like a support request than an issue, but I'm stumped.)

I've had burrow running against my cluster for a while, and all the HTTP endpoints seem to be returning good data except for the consumer status endpoint, which is never complete.

e.g.,

GET /v2/kafka/CLUSTER/consumer/GROUP/topic/TOPIC

```
{
    "error": false,
    "message": "consumer group topic offsets returned",
    "offsets": [
        22,
        ...snip...
```
(so I can see that there are offsets available)

GET /v2/kafka/CLUSTER/consumer/GROUP/status
```
{
    "error": false,
    "message": "consumer group status returned",
    "status": {
        "cluster": "CLUSTER",
        "complete": false,
        "group": "GROUP",
        "partitions": [],
        "status": "OK"
    }
}
```

But no partitions for the consumer group in the status? I'm using a very simple burrow.cfg:

```
[general]
logdir=/opt/burrow/log
logconfig=/opt/burrow/conf/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=zookeeper
port=2181

[kafka "CLUSTER"]
broker=broker
broker-port=9092
zookeeper=zooker
zookeeper-port=2181
zookeeper-path=/kafka

[httpserver]
server=on
port=8001
```

What could I be missing that would keep status from being available?

**Comment by iamnoah** [comment]
Derp. I misunderstood. partitions will only be populated if there are lagging partitions.

**Comment by toddpalino** [comment]
You've got it :)

Additionally, complete will be marked as false until there is a full ring of offsets. This means that if the number of intervals to check over is set to 10 (the default), and your consumer is only committing offsets every 10 minutes, it will take 100 minutes after Burrow starts up before it will have complete data to work with.

**Comment by iamnoah** [comment]
Still seeing some confusing behavior. I never seem to get to complete: true from the consumer group status endpoint. Perhaps relatedly, I have partitions where the consumer offset is at -1 (so never committed I guess) and but I get status: OK with no partitions listed. I know this is a bug in my code, but I would expect those partitions to show up as STOPed...

**Comment by toddpalino** [comment]
How often are your consumers committing their offsets? If you are seeing a -1 in the offsets list for some partitions, that's indicating that Burrow has never seen an offset committed for that partition by that consumer group. Once it has seen it once (provided the data is complete) it will reported it as a STOP if the consumer stops committing. Since you're not seeing it for all partitions, it sounds like perhaps you have an issue with the consumer where some of the partitions are not getting owned properly within the consumer group, or the particular consumer that owns them is not committing offsets due to a problem.

In general, as long as the data is incomplete, Burrow will report that everything's fine. So we need to figure out why your data is not getting complete?

**Comment by iamnoah** [comment]
So the -1s went away when I restarted my server, so that will remain a mystery.

My consumers commit every minute, if they have processed something. If they haven't then they don't commit anything... Do I need a dummy commit of the same offset to keep Burrow happy?

**Comment by toddpalino** [comment]
Definitely that will cause issues with Burrow, since it will end up reporting stalls for slow partitions. However, you can also run into problems with the broker expiring the offsets out if the consumer is not regularly committing them (even if they don't change). We ran into this early on with kafka-mirror-maker attempting to do this optimiztion for committing offsets, and we wound up having resets because the broker would expire out the offsets for partitions after a certain amount of time if they were not refreshed.
