### ISSUE TITLE
Support for Kafka 0.8.1.1?

### ISSUE THREAD

**Issue by armelbd** [linkedin/Burrow#147]
I assumed Kafka 0.8.1.1 was supported with Burrow 0.1.1 since Zookeeper offsets are supported. I'm not so sure now... When I try to start Burrow I get:

`[CRITICAL] Cannot start Kafka client for cluster local: kafka server: Request was for a topic or partition that does not exist on this broker.`

From what I read this is the error returned when __consumer_offsets doesn't exist. Since I don't have this topic with 0.8.1.1 Is there a workaround?

Either way the Wiki and Readme should explicitly mentioned which Kafka versions are supported

**Comment by toddpalino** [comment]
A quick workaround is just to create the topic, however you could run into some minor issues here if/when you upgrade in the future if the topic is not created appropriately (like with 100 partitions).

As for Burrow, this can be fixed with a config to enable/disable consuming the topic, with the default being to enable.

**Comment by dgqypl** [comment]
@toddpalino How to config consumer offsets commit to Zookeeper in Burrow 0.1.1? Thanks!
