### ISSUE TITLE
Burrow crashes if `__consumer_offsets` not yet exists

### ISSUE THREAD

**Issue by yewton** [linkedin/Burrow#17]
Hi,

I'm going to construct a Kafka cluster and monitor it with Burrow.

Just after Kafka installation, Burrow crashes with outputs below: 

```
Started Burrow at July 31, 2015 at 11:16pm (JST)
1438352170387870777 [Info] Starting Zookeeper client
1438352170387958149 [Info] Starting Offsets Storage module
1438352170388042830 [Info] Starting HTTP server
1438352170388103038 [Info] Starting Zookeeper client for cluster local
1438352170388130970 [Info] Starting Kafka client for cluster local
1438352170416477260 [Critical] Cannot start Kafka client for cluster local: kafka server: Unexpected (unknown?) server error.
Burrow failed at July 31, 2015 at 11:16pm (JST)
```

After create some topics and consume them to create `__consumer_offsets`, Burrow worked well.

**Comment by toddpalino** [comment]
This is expected behavior, as Burrow can't do most of its work without that topic. However, the larger problem is that there is no clean handling of the situation when the topic does not exist, which also means there is no proper handling of the case where there is a serious problem consuming. 

This will need a lot of work to add some error checking and retry behavior around the consumer.

**Comment by yewton** [comment]
That makes sense. Thank you.

As for me, It was hard to find the cause of the error and took some time...
More detailed error message like "Failed to get a partition count for the consumption topic" may be very helpful!

Thanks.
