### ISSUE TITLE
What does the config file for Burrow 1.0RC look like? panic No Zookeeper servers specified

### ISSUE THREAD

**Issue by daodennis** [linkedin/Burrow#260]
Without knowing Viper I didn't realize that .cfg or no extension will not work.  I strace'd and it's looking for one of a few extensions, toml seemed like the best candidate since it looks like the burrow.cfg form the pre-1.0 days, but it still doesn't seem to work. 

```
[pid 11975] stat("/home/dennis/burrow.json", 0xc420081148) = -1 ENOENT (No such file or directory) <0.000026>
[pid 11975] stat("/home/dennis/burrow.toml", 0xc420081218) = -1 ENOENT (No such file or directory) <0.000027>
[pid 11975] stat("/home/dennis/burrow.yaml", 0xc4200812e8) = -1 ENOENT (No such file or directory) <0.000024>
[pid 11975] stat("/home/dennis/burrow.yml", 0xc4200813b8) = -1 ENOENT (No such file or directory) <0.000025>
[pid 11975] stat("/home/dennis/burrow.properties", 0xc420081488) = -1 ENOENT (No such file or directory) <0.000025>
[pid 11975] stat("/home/dennis/burrow.props", 0xc420081558) = -1 ENOENT (No such file or directory) <0.000023>
[pid 11975] stat("/home/dennis/burrow.prop", 0xc420081628) = -1 ENOENT (No such file or directory) <0.000025>
[pid 11975] stat("/home/dennis/burrow.hcl", 0xc4200816f8) = -1 ENOENT (No such file or directory) <0.000025>
```

```
$ ./burrow_beta
Reading configuration from .
{"level":"info","ts":1510396387.319005,"msg":"Started Burrow"}
{"level":"info","ts":1510396387.3191428,"msg":"configuring","type":"coordinator","name":"zookeeper"}
{"level":"panic","ts":1510396387.3191752,"msg":"No Zookeeper servers specified"}
panic: No Zookeeper servers specified [recovered]
	panic: No Zookeeper servers specified [recovered]
	panic: No Zookeeper servers specified

goroutine 1 [running]:
main.handleExit()
	/Users/dennis/go/src/github.com/linkedin/Burrow/main.go:42 +0x293
panic(0x8f68e0, 0xc420254890)
	/usr/local/go/src/runtime/panic.go:491 +0x283
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc4200be420, 0x0, 0x0, 0x0)
	/Users/dennis/go/src/go.uber.org/zap/zapcore/entry.go:229 +0x52e
go.uber.org/zap.(*Logger).Panic(0xc42008cc60, 0x9e04f3, 0x1e, 0x0, 0x0, 0x0)
	/Users/dennis/go/src/go.uber.org/zap/logger.go:225 +0x7f
github.com/linkedin/Burrow/core.configureCoordinators.func1(0xc42008c7e0)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/burrow.go:89 +0x88
panic(0x8f68e0, 0xa38a20)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/linkedin/Burrow/core/internal/zookeeper.(*Coordinator).Configure(0xc42024edc0)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/internal/zookeeper/coordinator.go:48 +0x2a5
github.com/linkedin/Burrow/core.configureCoordinators(0xc42008c7e0, 0xc82860, 0xc42024edc0, 0xc82820, 0xc42024dd40, 0xc82460, 0xc4202602c0, 0xc824e0, 0xc420260320, 0xc825e0, ...)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/burrow.go:96 +0x9c
github.com/linkedin/Burrow/core.Start(0xc42008c7e0, 0xc42008cd20, 0x3)
	/Users/dennis/go/src/github.com/linkedin/Burrow/core/burrow.go:124 +0x324
main.main()
	/Users/dennis/go/src/github.com/linkedin/Burrow/main.go:93 +0x457
```

This is the zookeeper section:
```
[zookeeper]
hostname="zookeeper.dns"
port=2181
timeout=6
lock-path="/burrow/notifier"
```

**Comment by toddpalino** [comment]
Yeah, as you can see, Viper looks for multiple kinds of config files in the specified directory (defaults to .). Here's an example of my Zookeeper section in a TOML configuration file:

```
[zookeeper]
servers=["zk-hostname.linkedin.com:2181"]
root-path="/burrow-test-tpalino"
timeout=30
```

There's no longer a port config, and the servers config is an array of host:port pairs. The path is also now "root-path", as this can be used by multiple modules. The individual module (like the notifiers) will pick their own path under that root.

**Comment by toddpalino** [comment]
Here's a complete file that I'm using for testing. There's going to be some changes before this is final - like there should be a default for the storage and evaluator, so if you don't specify it in the config explicitly it doesn't fail.

```
[general]
pidfile="burrow.pid"

[logging]
filename="burrow.log"
level="info"

[zookeeper]
servers=["zk-hostname.linkedin.com:2181"]
root-path="/burrow-test-tpalino"
timeout=30

[httpserver.mine]
address=":8080"

[storage.default]
class-name="inmemory"
intervals=5
min-distance=1

[evaluator.default]
class-name="caching"
expire-cache=60

[client-profile.notls]
client-id="burrow-test-tpalino"
kafka-version="0.10.2"

[cluster.tracking]
class-name="kafka"
servers=["kafka-hostname.linkedin.com:9021"]
client-profile="notls"
topic-refresh=60

[consumer.tracking_kafka]
class-name="kafka"
cluster="tracking"
servers=["kafka-hostname.linkedin.com:9021"]
client-profile="notls"

[consumer.tracking_zk]
class-name="kafka_zk"
cluster="tracking"
servers=["zk-hostname.linkedin.com:2181"]
zookeeper-path="/kafka-tracking"
zookeeper-timeout=30

[notifier.connector]
class-name="http"
url-open="http://localhost:9090/"
url-close="http://localhost:9090/"
extras={api_key="mockapikey", app="mockapp", fabric="mydc", tier="stg"}
template-open="default-http-post.tmpl"
template-close="default-http-delete.tmpl"
threshold=1
interval=60
send-close=true
```

**Comment by daodennis** [comment]
Thanks for this! What do the email and slacknotifier sections look like?

**Comment by daodennis** [comment]
Also, what is the difference between the zookeeper-path in the consumer section vs in the zookeeper section?

**Comment by marcosArruda** [comment]
Hi guys, that changes should be put on the wiki. And the example codes.

**Comment by toddpalino** [comment]
@daodennis - For consumer modules, zookeeper-path is the path to the Kafka cluster that the consumer is for. This is the same as the zookeeper information in the cluster definition in 0.x. The zookeeper section of the config is a general zookeeper client that is used for coordination of Burrow itself (so it's not a particular Kafka cluster).

email and slack notifier sections are similar to the HTTP section I showed. The `class-name` is either "email" or "slack".

All notifiers use the following config keys:
class-name (string - type of notifier)
interval (int - number of seconds between sending out reports)
threshold (int - status threshold to send reports for. 1=OK, 2=WARN, 3=ERR)
group-whitelist (regexp - groups to send notifications for)
group-blacklist (regexp - groups to NOT send notifications for - processed second)
extras (map of string->string - extra parameters passed into the templates)
send-close (bool - whether or not to send notifications when an group transitions to OK)
template-open (filename - template to use to create messages for a group)
template-close (filename - template to use for close messages when send-close is true)

http uses the following additional keys:
timeout (int - timeout in seconds for the HTTP client)
keepalive (int - number of seconds to keep the HTTP connection open and reuse)
url-open (string - URL to use when sending notifications)
url-close (string - URL to use for close messages when send-close is true)
method-open (string - HTTP method to use, like "POST")
method-close (string - HTTP method to use, like "POST")

email uses the following additional keys:
server (string - SMTP server to use)
port (int - port number to connect to on the SMTP server)
auth-type (string - blank for no auth, otherwise "plain" or "crammd5")
username (string - username for auth)
password (string - password for auth)
from (string - email address to send messages from)
to (string - email address to send messages to)

slack uses the following additional keys:
timeout (int - timeout in seconds for the HTTP client)
keepalive (int - number of seconds to keep the HTTP connection open and reuse)
token (string - authentication token for slack)
channel (string - channel identifier to send messages to)
username (string - username to send messages as)
icon-emoji (string - emoji, like ":shrug:" to use as the icon)
icon-url (string - URL to an image to use as the icon)

**Comment by toddpalino** [comment]
Note that in the config section headings, the part after the dot is a unique identifier for the module within that section (so all notifiers need a unique name, for example). This is strictly required for the cluster modules, as those names are referenced elsewhere. But it might be worth dropping them for the other modules and just making the config an array of sections, rather than having unique names)

**Comment by daodennis** [comment]
Why are there separate consumer configurations, can they be merged?
```
[consumer.tracking_kafka]
class-name="kafka"
cluster="tracking"
servers=["kafka-hostname.linkedin.com:9021"]
client-profile="notls"

[consumer.tracking_zk]
class-name="kafka_zk"
cluster="tracking"
servers=["zk-hostname.linkedin.com:2181"]
zookeeper-path="/kafka-tracking"
zookeeper-timeout=30
```
Can these just be optionally part of the cluster? Would this be functionally the same:

```
[cluster.tracking]
class-name="kafka"
kafka_servers=["kafka-hostname.linkedin.com:9021"]
zookeeper_servers=["zk-hostname.linkedin.com:2181"]
zookeeper-paths=["/kafka-tracking"]
client-profile="notls"
topic-refresh=60
zookeeper-timeout=30
```
With that said, is there a situation where the [zookeeper] section and the servers line in the consumer section for kafka_zk be different and/or do they always have to be in sync?

**Comment by toddpalino** [comment]
The reason that they are separate is because they are separate modules inside of burrow now, rather than being part of a monolithic bit of code. While it makes the config more verbose, it keeps the code more consistent.

The zookeeper section is completely separate from the consumers, and does not have to match. The zookeeper section is where Burrow writes its own metadata - it doesn't have to be the same as any of the Kafka clusters.
