### ISSUE TITLE
Strange status/lag behaviour

### ISSUE THREAD

**Issue by padilo** [linkedin/Burrow#287]
We had some strange problem, that seems to be a bug, but not sure about.

We have a consumer that is consuming from just one topic, and during  a period of time it hapens the following:
![image](https://user-images.githubusercontent.com/783959/33428354-c167d286-d5c8-11e7-93ee-4b338d18aaf8.png)

Consumer status 3 corresponds to a ERROR state.

According to the rules in the wiki evaluation rules, if lag is 0, status should be OK (which in this chart is 0).

After we realize something is wrong we redeploy the consumer and suddenly burrow showed a 55k lag. But we didn't produce that so many messages at this specific time, seems to be the number of messages while the consumer status was at ERROR state.

We don't know what exactly happens on that period, and seems that according to rules this shouldn't happen.
Is this a bug?
Is this a missing part in the documentation?
What do you think it happened?

The charts are extracted data from http burrow API of the values from [consumer_lag](https://github.com/linkedin/Burrow/wiki/http-request-consumer-group-status), fields: `status.status` and `status.totallag`

**Comment by toddpalino** [comment]
What you ran into is a non-intuitive way the lag works in Burrow when partitions are stopped. Burrow only updates lag at the time of a consumer commit, so if there are no longer commits coming in, the lag is not updated. This means that when partitions are stopped, the lag number does not update. It's for this reason that you should work off the consumer and partition status information, and not the lag directly.

Note that this is fixed in the new version (being promoted to the master branch today), so the lag numbers will update even when the consumer is stopped.

**Comment by jrpilat** [comment]
Heya @toddpalino, thanks for making Burrow! Is it still the case that the lag for a partition will be increased, if the broker offset increases, but no consumer offset is committed (the partition is "stopped")?
