### ISSUE TITLE
Unable to get /v2/kafka/(cluster)/consumer/(group)/status

### ISSUE THREAD

**Issue by DavidLiuXh** [linkedin/Burrow#32]
Always show "complete":false,"partitions":[],"maxlag":[] when get /v2/kafka/(cluster)/consumer/(group)/status

By updated addConsumerOffset function in offsets_store.go file to solve this problem：

if offset.Timestamp-previousTimestamp < (storage.app.Config.Lagcheck.MinDistance * 1000) {
			storage.offsets[offset.Cluster].consumerLock.Unlock()
			return
		}

=>

if (offset.Timestamp-previousTimestamp) > 0 && (offset.Timestamp-previousTimestamp < (storage.app.Config.Lagcheck.MinDistance * 1000)) {
			storage.offsets[offset.Cluster].consumerLock.Unlock()
			return
		}

**Comment by toddpalino** [comment]
The `"complete":false` part is because Burrow has not yet seen the configured number of offsets (set in the `lagcheck` section with the `intervals` config) for that consumer group. This is correct behavior. If your consumer is committing offsets on 1 minute intervals, and `intervals` is set to 10, it will take 10 minutes before results are complete. If your offset commit interval is 10 minutes, it will take 1 hour and 40 minutes.

The change you made essentially only allows offsets to be stored where the timestamp does not change. This is bad behavior. This means that if a consumer committing offsets to Zookeeper stops committing offsets, either because it has hung or gone away, Burrow would continue to fill up the offsets ring for that consumer with offsets with the same timestamp and offset.

**Comment by DavidLiuXh** [comment]
Thanks for @toddpalino.

**Comment by DavidLiuXh** [comment]
If a consumer group has been a long did not commit offset when startup a Burrow, since "if offset.Timestamp-previousTimestamp < (storage.app.Config.Lagcheck.MinDistance * 1000)", 
this  "complete" value will always be "false" for get /v2/kafka/(cluster)/consumer/(group)/status

**Comment by DavidLiuXh** [comment]
if offset.Timestamp-previousTimestamp < (storage.app.Config.Lagcheck.MinDistance*1000)

=>

if storage.offsets[offset.Cluster].consumer[offset.Group][offset.Topic][offset.Partition].Value != nil && offset.Timestamp-previousTimestamp < (storage.app.Config.Lagcheck.MinDistance*1000)

Is this ok？
