### ISSUE TITLE
Issue on listing Consumers

### ISSUE THREAD

**Issue by tutunci** [linkedin/Burrow#33]
Hi Tod,
I've some kind of issue on listing Consumers. 
Asking about list of topics, status of topic and Offset is working fine:
http://8.8.8.8:8000/v2/kafka/druida/topic/buck_bidding
```
{
error: false,
message: "broker topic offsets returned",
offsets: [
331251579,
354084379,
349230371
]
}
```
But when I ask about Consumers result is empty
http://8.8.8.8:8000/v2/kafka/druida/consumer
```
{
error: false,
message: "consumer list returned",
consumers: [ ]
}
```
Looking inside Zookeeper I can see consumers section:
```
[zk: localhost:2181(CONNECTED) 0] ls /
[controller_epoch, controller, brokers, zookeeper, admin, consumers, burrow, druid-aws, config]
[zk: localhost:2181(CONNECTED) 1] ls /consumers
[druidaws2, druidaws]
```

Can you please drive me on doing proper checks?

Thanks
Maurizio

**Comment by toddpalino** [comment]
In general, there are one of two things going on here:

1 - These consumers are committing offsets to Zookeeper, and you have not configured checking for Zookeeper offsets
2 - These consumers are committing offsets to Kafka, but they have not been running since you last started Burrow, therefore they have not been detected

The solution for 2 is obvious - start the consumers. For 1, you need to enable the new Zookeeper offset checking that is available in master. To do this, you need to add the configuration line `zookeeper-offsets=true' in the `[kafka "druida"]` section in your config file, at minimum. This will enable code in Burrow that will scan the Zookeeper offsets and collect them ever minute.
