### ISSUE TITLE
Slack http notifications

### ISSUE THREAD

**Issue by panda87** [linkedin/Burrow#48]
Any suggestions what should I need to add \ change in the basic http notifier .tmpl file in order to send notification to Slack?

In addition, how can I send to different http notifications to different http end points like the email support.

Thanks

**Comment by toddpalino** [comment]
I've not worked with the Slack API yet, so I'm not sure exactly what request you need. The templating is designed so that you can set up the proper POST request you need.

At present, Burrow does not support multiple HTTP notifiers. It's not a bad idea, but I think it would require a significant refactor. Currently. consumer status is calculated either on request (via the API), or periodicially by either the email or HTTP notifier. It should be changed so that the status is calculated periodically by one routine, and those results are shared by all notifiers.

**Comment by panda87** [comment]
Yup, sounds like desired behave!
