### ISSUE TITLE
performance of burrow with clusters that process large amounts of traffic

### ISSUE THREAD

**Issue by daodennis** [linkedin/Burrow#539]
Hi,

How many offsets can Burrow process per core from a Kafka cluster? Are there known or possible performance limitations that might require Burrow to be a part of a consumer group to consume from `__consumer_offsets` ? Has Linkedin or other companies run into these limitations and if so what have they done to work around it?

**Comment by weeco** [comment]
I believe I can give you some insights here. I created a Kafka Exporter which works similiarly to Burrow but is more performant (also because it does not as many things as Burrow does).

In my test clusters I am limiting Burrow and Kafka Minion (https://github.com/cloudworkz/kafka-minion) both to 2 CPU cores. Kafka Minion can process 100-120k offsets / second while Burrow processed something around 40-50k / second.

However I do not believe this is something you need to be concerned about. In my kafka cluster I get 1k consumer offsets / second. Since this is a compacted topic where the consumer group id is the key, you don't have to worry too much about the number of offset messages to be processed. It takes something like 5-10 minutes to process all these offset messages which shouldn't be a problem unless you expect regular restarts/crashes.

**Comment by daodennis** [comment]
Thank you that clears a lot of things up!

**Comment by daodennis** [comment]
It's the two year anniversary of this particular bug and originally I received a great answer I don't think any further action is needed that hasn't happened already, and the software and Kafka may have changed enough to make this a moot question anyway, but I'm not so sure of the latter.
