### ISSUE TITLE
Lag does not update when status is STOP

### ISSUE THREAD

**Issue by bencampion** [linkedin/Burrow#58]
If I stop a consumer group, then the status of that group reported by Burrow changes to `STOP`, which is what I'd expect. However the lag reported by Burrow for that group remains at the value it was before I stopped the group even though new messages are being sent to the topic. When I start the consumer group again then the lag values are updated.

Is this intended behaviour? Ideally I'd like to know what the lag is even when the group is stopped.

**Comment by toddpalino** [comment]
At the moment, this is by design. The lag value for a consumer partition is calculated and saved when the offset commit is recorded. If there are no offset commits, there is no change to the lag value.

There was a discussion elsewhere about changing where lag is calculated (doing it when the current offset is retrieved from the brokers via the OffsetRequest, rather than when the consumer commits their offsets). However, recording this with the current offset storage model could be difficult without interfering with other things. It might make more sense to have a "last lag" value for the partition that is not related to the offset ring.

**Comment by bencampion** [comment]
Thanks for explaining. Feel free to close the issue if it's by design.

Great app, by the way. It's much better than the threshold based lag checks I've used in the past.

**Comment by toddpalino** [comment]
Thanks for the feedback! The failures of thresholding is exactly why we ended up writing this one.

If you'd like to contribute fixes or enhancements, we're always reviewing and accepting PRs. We have some work in progress internally at LinkedIn that I'll be committing soon that will hopefully make it a lot easier to do more of the "total lag" monitoring.
