### ISSUE TITLE
ConsumerGroup completeness and offset timing

### ISSUE THREAD

**Issue by unclethan** [linkedin/Burrow#61]
If I want to commit my consumergroup offset after processing each message (to minimize re-processed messages on crash/restart etc), how do I configure my lagcheck `interval` to get a `complete` of `true`.

**Comment by toddpalino** [comment]
The consumer group will be considered complete as soon as there are `interval` number of offset commits for each partition being consumed. You may need to use the `min-distance` config in order to prevent offsets from being recorded too quickly (which can cause a conflict with the frequency of broker offset fetches, and generate spurious errors).

**Comment by unclethan** [comment]
I double-checked my min-distance and interval, which were both correct. However, one of partitions was not being written to, which resulted in a lack of completeness.  Fixing that resulted in a `complete` of `true`

Thanks!
