### ISSUE TITLE
How can I test Burrow?

### ISSUE THREAD

**Issue by raseshdesaiexp** [linkedin/Burrow#73]
Hello,

I am running burrow to monitor our lab (or test) kafka environment and when I check status using the status endpoint {http://localhost:8000/v2/kafka/lab/consumer/(group)/status} it says status=OK (though complete=false for a long time as pointed out in previous issue that someone submitted just before this one) and I receive no emails. One possible reason is that all consumer groups/topics/partitions in our lab kafka environment are most likely functioning well. 

My question is how can I trigger a behavior that one of the kafka consumer slows down or stops reading messages on a specific partition so I can check if burrow is sending out an email to me or when I use the status endpoint it shows me status=WARNING/ERROR vs OK. 

Thoughts/Suggestions...?

-Rasesh

**Comment by toddpalino** [comment]
The `complete=false` issue is generally because there have not been enough offset commits for Burrow to consider the information complete (a minimum of `interval` commits, as you have configured in Burrow). This could easily happen if the consumers are committing to Zookeeper, and not Kafka, and some of the topics are slow. The ZK offset commit logic in the Kafka client shortcuts commits if the offset hasn't changed.

The easiest way to test, once you have complete data, is to just shut down one of the consumer groups so it will go into a stopped state. This should generate an error.

**Comment by raseshdesaiexp** [comment]
Thank you, I'll try that out. Any specific recommendations on testing consumer slowing down or a specific partition failure when consumer is processing other partitions as expected?

**Comment by toddpalino** [comment]
There's not much you can do here without implementing the behavior in your consumer.
