### ISSUE TITLE
The granularity of httpnotifier

### ISSUE THREAD

**Issue by oyld** [linkedin/Burrow#75]
I think http notifier should monitor according to topic.
For example, I want to monitor topic A and group X, but I don't want to monitor topic B and group X.
I think it is neccesary, what do you think?

**Comment by toddpalino** [comment]
The goal of Burrow is to monitor all topics for each consumer, so that the status presented is a complete view. There's already a request, issue #46, to have a group whitelist to go along with the blacklist. I'm not certain that configuring specific group and topic tuples to monitor would be a good choice. It would lead to a fairly brittle configuration.

Can you expand on the particular use case here?
