### ISSUE TITLE
the lag partition will be disappear when partition lag in HTTP Endpoint

### ISSUE THREAD

**Issue by lueliu** [linkedin/Burrow#96]
I use magnetme/burrow image in docker.

a topic with 3 partition in kafka-manager ( 2 lag in 3 partition )
```
Partition	LogSize	            Consumer Offset      	Lag	     Consumer Instance Owner
0	      6364656638	      6363465115	      1191523	      srv-1-21547-1468675603-2
1	      6381575297	      6381576848	      -1551	          srv-1-21547-1468675603-3
2	      6363776990	      6361571868	      2205122	      srv-1-21547-1468675603-1   
```
however, the lag partition disappeared in burrow. I remember I had to restart the container. so is there a problem?  I checked zookeeper,anything is ok.
```
# curl -G  http://X.X.X.X:8000/v2/kafka/local/consumer/gps_consumer/lag |jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
124   372  124   372    0     0   133k      0 --:--:-- --:--:-- --:--:--  363k
{
  "status": {
    "maxlag": null,
    "partitions": [
      {
        "end": {
          "lag": 0,
          "timestamp": 1468684935903,
          "offset": 6381598640
        },
        "start": {
          "lag": 0,
          "timestamp": 1468684395979,
          "offset": 6381401682
        },
        "status": "OK",
        "partition": 1,
        "topic": "topic.gps"
      }
    ],
    "complete": false,
    "status": "OK",
    "group": "gps_consumer",
    "cluster": "local"
  },
  "message": "consumer group status returned",
  "error": false
}
```

**Comment by lueliu** [comment]
It is strange that  I found the display to normal in HTTP Endpoint next day.

**Comment by toddpalino** [comment]
It's because you restarted Burrow. The request where it says that it's in a good state was while Burrow was still building up the offset commit history for the consumer again. Once there were enough offset commits (defined by the `interval` value in your config), it reported normally again.

Generally, when the `complete` flag in the response is `false`, you should not trust that the response is accurate. This flag indicates that Burrow does not enough offset commits to do a complete status evaluation for the consumer.
